# Generated by Django 4.2.7 on 2025-01-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumanKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('VATANDASLIK', 'Vatandaşlık'), ('OTURMA_IZNI', 'Oturma İzni'), ('GENEL', 'Genel')], max_length=50)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doküman Kategorisi',
                'verbose_name_plural': 'Doküman Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='DokumanTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kod', models.CharField(blank=True, max_length=50, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('zorunlu', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dokuman.dokumankategori')),
            ],
            options={
                'verbose_name': 'Doküman Tipi',
                'verbose_name_plural': 'Doküman Tipleri',
                'ordering': ['kategori', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Dokuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='dokumanlar/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('dokuman_tipi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokuman.dokumantipi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumanlar', to='musteri.customer')),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
            },
        ),
        migrations.CreateModel(
            name='BasvuruSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_tipi', models.CharField(choices=[('VATANDASLIK', 'Vatandaşlık'), ('OTURMA_IZNI', 'Oturma İzni')], max_length=50)),
                ('baslangic_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('randevu_tarihi', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('BASLANGIC', 'Başlangıç'), ('BELGE_TOPLAMA', 'Belge Toplama'), ('INCELEME', 'İnceleme'), ('RANDEVU_BEKLENIYOR', 'Randevu Bekleniyor'), ('BASVURU_YAPILDI', 'Başvuru Yapıldı'), ('TAMAMLANDI', 'Tamamlandı'), ('REDDEDILDI', 'Reddedildi')], default='BASLANGIC', max_length=20)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_surecleri', to='musteri.customer')),
            ],
            options={
                'verbose_name': 'Başvuru Süreci',
                'verbose_name_plural': 'Başvuru Süreçleri',
            },
        ),
    ]
