# Generated by Django 4.2.7 on 2025-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yapilacak',
            name='son_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
